# config/packages/security.yaml
security:
  # ...
  password_hashers:
    App\Entity\Employee:
      algorithm: auto # L'algorithme "auto" sélectionne le meilleur algorithme disponible
      cost: 12 # La valeur de coût pour l'algorithme bcrypt, ajustez selon vos besoins
  # ...
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Employee
        property: username
  # ...
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      logout:
        path: app_logout
      form_login:
        login_path: login
        check_path: login
  # ...
  access_control:
    # - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
